physalisproject/physalisproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap, ProblemSitemap, FlatPageSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'problem': ProblemSitemap,
    'flatpages': FlatPageSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('problems/', include('problems.urls', namespace='problems')),
    path('types/', include('typesinege.urls', namespace='typesinege')),
    path('variants/', include('variants.urls', namespace='variants')),
    path('tags/', include('tags.urls', namespace='tags')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

physalisproject/tags/urls.py
from django.urls import path

from . import views

app_name = 'tags'
urlpatterns = [
    path('', views.TagsView.as_view(), name='list'),
    path('<slug:slug>', views.ProblemsView.as_view(),
         name='problems')
]

physalisproject/templates/includes/footer.html
<footer>
  <hr /> © phys.pro, {% now "Y" %}
</footer>

physalisproject/templates/includes/mj.html
    <script>
      window.MathJax = {
        tex: {
          processEscapes: true,
          inlineMath: [['$', '$']],
          macros: {
            eds: "\\mathcal{E}",
            la: "\\lambda",
            Ftr: "F_\\textsf{тр}",
            tg: "\\text{tg}",
            ctg: "\\text{ctg}",
            arctg: ["\\text{arctg}\\; #1", 1],
            a: "\\alpha",
            b: "\\beta",
            f: "\\varphi",
            tga: "\\tg{\\alpha}",
            ctga: "\\ctg{\\alpha}",
            tgb: "\\tg{\\beta}",
            tgf: "\\tg{\\varphi}",
            sina: "\\sin{\\alpha}",
            cosa: "\\cos{\\alpha}",
            sinb: "\\sin{\\beta}",
            cosb: "\\cos{\\beta}",
            sinf: "\\sin{\\varphi}",
            cosf: "\\cos{\\varphi}",
            dx: "\\Delta x",
            dE: "\\Delta E",
            dU: "\\Delta U",
            dT: "\\Delta T",
            dt: "\\Delta t",
            deg: "^\\circ",
            N: "\\;\\textsf{Н}",
            kg: "\\;\\textsf{кг}",
            me: "\\;\\textsf{м}",
            ms: "\\;\\textsf{м}/\\textsf{с}",
            cms: "\\;\\textsf{см}/\\textsf{с}",
            sec: "\\;\\textsf{с}",
            degc: "\\,{}^\\circ\\text{C}"
          }
        }
      };
    </script>

physalisproject/templates/includes/nav.html
<nav class="no-print">

  <div class='nav-left'>
    {% comment %}
    {% if request.user.is_staff %}
    <a href="/admin/">Admin</a>
    {% endif %}
    {% endcomment %}
    <a href="/"{% if request.path == '/' %} class='current_nav'{% endif %}>Главная</a>
    <a href="/articles/"{% if '/articles' in request.path %} class='current_nav'{% endif %}>Статьи</a>
    <a href="/courseware/"{% if '/courseware/' in request.path %} class='current_nav'{% endif %}>Материалы</a>
    <a href="/about/"{% if '/about/' in request.path %} class='current_nav'{% endif %}>О</a>
    <a href="/school/"{% if '/school/' in request.path %} class='current_nav'{% endif %} class=hi_link>Школа</a>
  </div>

  <div class="nav-right">
    <a href="{% url 'tags:list'%}"{% if '/tags/' in request.path %} class='current_nav'{% endif %}>Тэги</a>
    <a href="{% url 'typesinege:list'%}"{% if '/types/' in request.path %} class='current_nav'{% endif %}>Типы</a>
    <a href="{% url 'problems:list'%}"{% if '/problems/' in request.path %} class='current_nav'{% endif %}>Задачи</a>
    <a href="{% url 'variants:list'%}?order_by=-id"{% if '/variants/' in request.path %} class='current_nav'{% endif %}>Варианты</a>
    {% if '/problems/' in request.path and request.path != '/problems/' and request.user.is_staff %}
    <a href="/admin/problems/problem/{{problem.id}}/change" class=bold>✎</a>
    {% elif '/variants/' in request.path and request.path != '/variants/' and request.user.is_staff %}
    <a href="/admin/variants/variant/{{variant.id}}/change" class=bold>✎</a>
    {% elif request.path != '/problems/' and request.path != '/variants/' and not '/types/' in request.path and request.user.is_staff %}
    <a href="/admin/flatpages/flatpage/{{flatpage.id}}/change/" class=bold>✎</a>
    {% endif %}
  </div>

</nav>

physalisproject/templates/includes/pagination.html
{% load save_parameters %}

{% if page_obj.paginator.num_pages != 1 %}
<div class="center-flex"> <h3>Выберите страницу</h3> </div>
<div class="center-flex mb10 mt-5 sans fs12"> 
  {% for page_number in page_obj.paginator.page_range %}
    <a
      href="?{% param_save page=page_number %}"
      class="page {% if page_number == page_obj.number %}current{% endif %}">
      {{page_number}}
    </a>
  {% endfor %}
</div>
{% endif %}